### ISSUE TITLE
Question: how does it compare to ndarray-blas?

### ISSUE THREAD

**Issue by Bondifrench** [jacobbogers/blasjs#1]
Just discovered this library, how does this project compare to [Ndarray-blas](https://github.com/scijs?utf8=%E2%9C%93&q=blas&type=&language=)?
Ndarrays are strided arrays for easier tensors manipulations.

Would be great to see perf comparisons between the two.

**Comment by jacobbogers** [comment]
1. Looks like "ndarray-blas"  is an aborted project with only 1.6% of BLAS ported. (BLAS is over 250 functions).
2 It is well known BLAS subroutines, inherently uses strided arrays, (as is evident from the extensive readme) so any aborted (in case of ndarray-blas) BLAS implementation needs to use it too to stay compliant.

**Comment by jacobbogers** [comment]
just checked the ndarray-blas implementation, its basically nonexistent, 7 functions implemented out of 149

dasum/  dcopy/  gaxpy/  lib/          README.md  saxpy/
daxpy/  gasum/  gcopy/  package.json  sasum/     scopy/
